In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime
from sqlalchemy import create_engine
import folium
import requests
import json
import re
from tqdm.auto import trange
import time
from requests.exceptions import JSONDecodeError

In [ ]:
geocode_api = 'my_api_key'

In [ ]:
# Create a world map zoomed in on NJ level 4
nj_map = folium.Map(location=[40.05832, -74.40566], zoom_start=7.5)

# Dsiplay the map
nj_map

In [ ]:
# Create a sql connection to import the sales data and town central lat and long data
tax_engine = create_engine(f"postgresql+psycopg2://postgres:pw@hostname:5433/nj_tax_assessor")  # Connection for sqlalchemy to get data

query = f'SELECT * FROM gsmls_imputed_data WHERE "YEAR" >= 2019;'
test_data = pd.read_sql_query(query, tax_engine)

In [ ]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423470 entries, 0 to 423469
Columns: 149 entries, MLSNUM to year_built
dtypes: bool(102), datetime64[ns](2), float64(23), int64(8), object(14)
memory usage: 193.0+ MB

In [ ]:
test_data.columns

Index(['MLSNUM', 'STATUS_SHORT', 'ADDRESS', 'TOWN', 'COUNTY', 'ZIPCODE',
       'NJ_TOWNCODE', 'TOWNCODE', 'COUNTYCODE', 'BLOCKID',
       ...
       'WATER_WATRXTRA', 'UTILITIES_ALLUNDER', 'UTILITIES_ELECTRIC',
       'UTILITIES_GASNATUR', 'UTILITIES_GASINSTR', 'UTILITIES_GASPROPN',
       'LISTING_REMARKS', 'TAX_PATTERN', 'building_sqft', 'year_built'],
      dtype='object', length=149)

In [ ]:
pd.set_option('display.max_columns', 999)

In [ ]:
# Add AGE_OF_PROPERTY column
target_cols = ['MLSNUM', 'STATUS_SHORT', 'ADDRESS', 'TOWN', 'COUNTY', 'ZIPCODE',
               'LISTPRICE', 'OLP/LP%', 'SALESPRICE', 'LISTDATE', 'CLOSEDDATE',  'year_built',
               'STYLEPRIMARY_SHORT', 'ROOMS', 'BEDS', 'BATHSTOTAL', 'building_sqft', 'LOTSIZE (SQFT)',
               'DAYSONMARKET', 'CONDITION', 'DISTRESSED_SALE', 'TAXAMOUNT', 'LATITUDE',
               'LONGITUDE']

In [ ]:
test_data = test_data[target_cols]

In [ ]:
test_data.rename(columns={'LATITUDE': 'PROP_LATITUDE', 'LONGITUDE': 'PROP_LONGITUDE'}, inplace=True)

In [ ]:
test_data.head()

,MLSNUM,STATUS_SHORT,ADDRESS,TOWN,COUNTY,ZIPCODE,LISTPRICE,OLP/LP%,SALESPRICE,LISTDATE,CLOSEDDATE,year_built,STYLEPRIMARY_SHORT,ROOMS,BEDS,BATHSTOTAL,building_sqft,LOTSIZE (SQFT),DAYSONMARKET,CONDITION,DISTRESSED_SALE,TAXAMOUNT,PROP_LATITUDE,PROP_LONGITUDE
0,1000032,SD,26 Woodward,Montgomery Twp,Somerset,08502,269900,-4.0,261500.0,1996-07-02,1996-12-19,NaN,Colonial,8.0,4.0,2.1,NaN,43560.0,140.0,Unknown,False,4762.0,40.448303,-74.644115
1,1000108,SD,27 Cedar Grove Lane,Franklin Twp,Somerset,08873,199000,0.0,190500.0,1996-05-21,1996-09-19,1978.0,Custom,8.0,4.0,2.0,2356.0,113256.0,64.0,Unknown,False,4106.0,40.531870,-74.511363
2,1000110,SD,21 Lebed Drive,Franklin Twp,Somerset,08873,164900,0.0,156000.0,1996-03-20,1996-10-07,1966.0,Develpmt,6.0,3.0,2.0,1900.0,14810.4,161.0,Unknown,False,3057.0,40.494261,-74.492888
3,1000145,SD,1408 Boxwood Trail,Branchburg Twp,Somerset,08876,144000,0.0,135250.0,1996-07-03,1996-07-19,1990.0,TwnEndUn,6.0,2.0,2.1,1642.0,43560.0,0.0,Unknown,False,2378.0,40.570645,-74.703989
4,1000190,SD,59 Highview Avenue,Bernardsville Boro,Somerset,07924,319719,-8.0,282000.0,1996-05-17,1997-05-12,1980.0,Colonial,8.0,4.0,2.1,1970.0,11325.6,328.0,Unknown,False,4333.0,40.724179,-74.566354

In [ ]:
test_data.loc[302145]

MLSNUM                            2766651
STATUS_SHORT                           SD
ADDRESS                      38 Grant Ave
TOWN                         Clifton City
COUNTY                            Passaic
ZIPCODE                        07011-3512
LISTPRICE                          289900
OLP/LP%                               0.0
SALESPRICE                       250000.0
LISTDATE              2010-04-23 00:00:00
CLOSEDDATE            2010-12-20 00:00:00
year_built                         1941.0
STYLEPRIMARY_SHORT                CapeCod
ROOMS                                 6.0
BEDS                                  3.0
BATHSTOTAL                            1.1
building_sqft                      1288.0
LOTSIZE (SQFT)                     4791.6
DAYSONMARKET                         40.0
CONDITION                         Unknown
DISTRESSED_SALE                      True
TAXAMOUNT                          6882.0
PROP_LATITUDE                   40.879721
PROP_LONGITUDE                 -74.158055
Name: 302145, dtype: object

In [ ]:
test_sample = test_data.loc[302145]

In [ ]:
"""
I'll use the following guidelines to label comps and superior, eqyal and inferior
1) Location
  ***Use https://www.census.gov/data/academy/data-gems/2025/rural-or-urban-area.html
  - Label the area as urban, suburban or rural
  a. Comps in urban areas should be <= 0.5 miles
  b. Comps in suburban areas should be <= 1 mile
  c. Comps in rural areas should be <= 5 miles

2) Property Type
  - Only compare SFH to SFH or Condo to Condo

3) Size
  - Gross Living Area
  a. 0 - 1000 : +/- 25%
  b. 1001 - 2000 : +/- 20%
  c. 2001 - 3500 : +/- 15%
  d. 3501 - 5000 : +/- 10%
  e. 5000+ : +/- 10%

  - Lot size
  a. < 1 acre : +/- 30%
  b. 1-2.9 acres : +/- .5 acre
  c. 3-5.9 acres : +/- 1 acre
  d. 6-10.9 acres : +/- 2 acre
  e. 11+ acres : +/- 20%

4) Age
  a. 0 - 10 years : +/1 5 years
  b. 11 - 30 years : + 10 years/ -1/2 target age
  c. 30 - 50 years : +/15 years
  d. 51 - 75 years : +/20 years
  e. 75+ years : +/25 years

5) Physical Characteristics
  - Should have the same bedrooms and bathrooms
  - Quality changes +/-1 bedroom or bathroom?
  - Quality changes +/- 3 rooms
"""

In [ ]:
comp_properties = test_data.loc[(test_data['TOWN'] == test_sample['TOWN']) & (test_data['COUNTY'] == test_sample['COUNTY']) & (test_data['STATUS_SHORT'] == 'SD')
                                    & ( test_data['CLOSEDDATE'] <= test_sample['LISTDATE']) & (test_data['CLOSEDDATE'] > test_sample['LISTDATE'] - pd.Timedelta(days=90))]

In [ ]:
comp_properties.head()

,MLSNUM,STATUS_SHORT,ADDRESS,TOWN,COUNTY,ZIPCODE,LISTPRICE,OLP/LP%,SALESPRICE,LISTDATE,CLOSEDDATE,year_built,STYLEPRIMARY_SHORT,ROOMS,BEDS,BATHSTOTAL,building_sqft,LOTSIZE (SQFT),DAYSONMARKET,CONDITION,DISTRESSED_SALE,TAXAMOUNT,PROP_LATITUDE,PROP_LONGITUDE
264610,2563670,SD,192 Hazel St,Clifton City,Passaic,07011,210000,-37.0,193000.0,2008-07-01,2010-04-08,1920.0,Colonial,7.0,4.0,3.0,1287.0,3750.00,342.0,Unknown,False,5996.0,40.884379,-74.159485
269699,2664248,SD,24 West Parkway,Clifton City,Passaic,07014,899900,-8.0,775000.0,2009-03-18,2010-02-10,NaN,Custom,12.0,4.0,3.2,NaN,19602.00,237.0,Unknown,False,18365.0,40.843651,-74.143077
271279,2601930,SD,584 Clifton Avenue,Clifton City,Passaic,07011,190000,-46.0,192500.0,2008-11-12,2010-02-16,1926.0,Colonial,6.0,4.0,2.0,1214.0,3565.00,437.0,Unknown,True,6460.0,40.873323,-74.150952
276312,2707906,SD,28 Starmond Ave,Clifton City,Passaic,07013,294900,-6.0,275000.0,2009-08-20,2010-03-18,1929.0,Colonial,6.0,3.0,1.1,1492.0,3920.40,78.0,Unknown,False,7695.0,40.865152,-74.162735
276320,2708379,SD,115 Colfax Ave,Clifton City,Passaic,07013-1847,335000,-4.0,335000.0,2009-08-22,2010-01-26,1947.0,CapeCod,6.0,3.0,2.0,1540.0,6534.00,103.0,Unknown,False,6008.0,40.866672,-74.155050
277500,2715258,SD,12 Jaskot Ln,Clifton City,Passaic,07012-1105,349999,-5.0,330000.0,2009-09-19,2010-04-16,1955.0,CapeCod,7.0,4.0,1.1,1414.0,4791.60,163.0,Unknown,False,6817.0,40.853587,-74.150519
279594,2666794,SD,358 S Pky,Clifton City,Passaic,07014,350000,-12.0,315000.0,2009-03-23,2010-03-18,NaN,Colonial,7.0,3.0,1.1,NaN,6098.40,315.0,Unknown,False,7548.0,40.841577,-74.137393
281831,2669159,SD,544 Piaget Ave.,Clifton City,Passaic,07011,319000,-6.0,290000.0,2009-03-30,2010-03-29,1961.0,Bi-Level,9.0,4.0,2.0,1858.0,5400.00,164.0,Unknown,False,6934.0,40.878143,-74.158468
286945,2726778,SD,338 Mount Prospect Ave,Clifton City,Passaic,07012-1014,339000,0.0,316000.0,2009-11-09,2010-04-16,NaN,CapeCod,7.0,4.0,1.1,NaN,20808.00,129.0,Unknown,False,7885.0,40.856857,-74.160758
287428,2723738,SD,97 Sherwood St,Clifton City,Passaic,07013-1307,379000,0.0,350000.0,2009-10-26,2010-04-01,1948.0,Colonial,8.0,4.0,2.0,1536.0,4791.60,109.0,Unknown,False,8648.0,40.886766,-74.175695
287645,2729523,SD,22 Heights Rd,Clifton City,Passaic,07012-1215,669000,-9.0,640000.0,2009-11-23,2010-04-12,1940.0,Tudor,10.0,4.0,2.2,2768.0,9147.60,98.0,Unknown,False,11875.0,40.846766,-74.143712
287739,2725511,SD,39 Viola Ave,Clifton City,Passaic,07011-4211,239000,-4.0,230000.0,2009-11-02,2010-04-19,1925.0,Colonial,6.0,4.0,1.0,1496.0,3484.80,130.0,Unknown,False,5754.0,40.872346,-74.149912
287958,2728380,SD,65 La Salle Ave,Clifton City,Passaic,07013-2944,349000,0.0,320000.0,2009-11-16,2010-01-25,1950.0,Colonial,6.0,3.0,1.2,1582.0,4791.60,56.0,Unknown,False,6997.0,40.856366,-74.152382
288010,2728445,SD,15 Peru Rd,Clifton City,Passaic,07012-1642,359900,-5.0,346000.0,2009-11-17,2010-04-15,1920.0,Colonial,8.0,3.0,1.1,1294.0,4791.60,90.0,Unknown,False,7449.0,40.848825,-74.162457
290757,2714125,SD,506 Mount Prospect Ave,Clifton City,Passaic,07012-1372,695000,0.0,600000.0,2009-09-15,2010-03-05,NaN,Colonial,10.0,4.0,1.1,NaN,40075.20,84.0,Fixer Upper,True,10765.0,40.851686,-74.165023
291556,2704506,SD,17 Laurel Ave,Clifton City,Passaic,07012,565000,-9.0,535000.0,2009-08-05,2010-02-24,1930.0,Colonial,10.0,3.0,2.2,3622.0,8276.40,167.0,Unknown,False,9483.0,40.846439,-74.145557
291808,2710634,SD,85 Merselis Ave,Clifton City,Passaic,07011,99900,-41.0,94000.0,2009-09-01,2010-04-19,1947.0,HalfDupl,4.0,2.0,1.0,896.0,2178.00,206.0,Unknown,False,4692.0,40.885639,-74.136176
293693,2718122,SD,51 Maplewood Ave,Clifton City,Passaic,07013-1007,207000,0.0,237000.0,2009-10-01,2010-02-11,1928.0,Colonial,6.0,3.0,1.0,1084.0,3484.80,36.0,Unknown,False,6455.0,40.894866,-74.170099
293988,2722551,SD,222 Highview Dr,Clifton City,Passaic,07013-3331,379000,-10.0,360000.0,2009-10-20,2010-04-14,1953.0,SplitLev,8.0,4.0,1.1,1538.0,7107.00,140.0,Unknown,False,9208.0,40.859360,-74.175966
295240,2729625,SD,252 Riverwalk Way,Clifton City,Passaic,07014-1736,356900,-3.0,347000.0,2009-11-23,2010-04-16,2001.0,TwnEndUn,5.0,2.0,2.1,1487.0,17424.00,95.0,Fixer Upper,True,9556.0,40.823766,-74.131232
295253,2763228,SD,100 Dawson Ave,Clifton City,Passaic,07012-1102,300000,0.0,300000.0,2010-04-13,2010-04-14,1946.0,Colonial,8.0,3.0,2.0,1563.0,4791.60,0.0,Unknown,False,7483.0,40.852016,-74.148845
296002,2733040,SD,127 Merrill Rd,Clifton City,Passaic,07012-1611,329000,0.0,320000.0,2009-12-13,2010-04-01,1942.0,CapeCod,7.0,3.0,1.1,1323.0,5227.20,43.0,Unknown,False,7023.0,40.850238,-74.163285
296392,2737267,SD,375 Clifton Blvd,Clifton City,Passaic,07013-1806,339000,0.0,285000.0,2010-01-11,2010-04-16,1910.0,Colonial,7.0,3.0,1.0,1904.0,4356.00,59.0,Unknown,False,6977.0,40.868860,-74.156760
301920,2711872,SD,233 Luddington Ave,Clifton City,Passaic,07011,234500,-11.0,233000.0,2009-09-07,2010-04-08,1940.0,Colonial,8.0,3.0,1.1,1372.0,5662.80,134.0,Unknown,True,6507.0,40.876971,-74.153905
302288,2716144,SD,133 Cambridge Ct,Clifton City,Passaic,07014-1323,299000,-6.0,286000.0,2009-09-22,2010-02-09,1996.0,OneFloor,5.0,2.0,2.0,1030.0,31101.84,107.0,Unknown,False,5376.0,40.835854,-74.133462
303736,2723434,SD,39 Garrabrant Rd,Clifton City,Passaic,07013-1572,279900,-13.0,255000.0,2009-10-23,2010-04-14,1941.0,Ranch,6.0,3.0,2.0,1398.0,5227.20,117.0,Unknown,False,6567.0,40.879014,-74.180923
303806,2723709,SD,289 Hazel St,Clifton City,Passaic,07011-2812,196000,0.0,206000.0,2009-10-26,2010-03-09,1952.0,CapeCod,6.0,3.0,1.0,1305.0,5662.80,68.0,Unknown,False,5986.0,40.887694,-74.159794
304599,2729459,SD,56 Lorraine Dr,Clifton City,Passaic,07012-1255,379000,-5.0,362000.0,2009-11-22,2010-04-20,1959.0,SplitLev,7.0,3.0,2.0,1524.0,5227.20,113.0,Unknown,False,7354.0,40.848717,-74.150172

In [ ]:
def create_popup(proprty_details: pd.Series):

  property_details = proprty_details.loc[["STATUS_SHORT", "CONDITION", "STYLEPRIMARY_SHORT", "ADDRESS", "LISTPRICE", "OLP/LP%", "SALESPRICE",
                                          "ROOMS", "BEDS", "BATHSTOTAL", "building_sqft", "CLOSEDDATE", "DAYSONMARKET"]]

  html = property_details.to_frame().to_html()

  popup = folium.Popup(folium.Html(html, script=True), max_width=500)

  return popup

In [ ]:
def query_geocode(address, town, zipcode):

  pass_list = ['Jersey City']
  remove_pattern = re.compile(r'Town|Twp|Boro|Village')

  if town not in pass_list:
    town = re.sub(remove_pattern, '', town)

  address = address.replace(' ', '+')
  town = town.replace(' ', '+')

  final_address = f'https://geocode.maps.co/search?q={address}+{town}NJ+{zipcode}+US&api_key={geocode_api}'

  json_obj = requests.get(final_address).json()

  if json_obj == []:
    return None
  else:
    return float(json_obj[0]['lat']), float(json_obj[0]['lon'])

In [ ]:
def create_address(address, town, zipcode):

  return f'{address}, {town}, NJ {zipcode}'

In [ ]:
from textwrap import fill

def create_base_map(property_details: pd.Series=None, default_location=[40.05832, -74.40566], default_zoom_start=7.5):

    radius_dict = {
        '0.25 miles': {'fill_color': 'green', 'fill_opacity': 0.5, 'radius': 402.336},
        '0.5 miles': {'fill_color': 'green', 'fill_opacity': 0.25, 'radius': 804.672},
        '1 mile': {'fill_color': 'blue', 'fill_opacity': 0.25, 'radius': 1609.344},
        '2 miles': {'fill_color': 'blue', 'fill_opacity': 0.20, 'radius': 3218.688}
    }

    property_group = folium.FeatureGroup(name='Properties')

    # Create a base map
    if property_details is None:
      base_map = folium.Map(location=default_location, zoom_start=default_zoom_start)
    else:
      # lat, lon = query_geocode(property_details['ADDRESS'], property_details['TOWN'], property_details['ZIPCODE'])
      lat, lon = property_details['PROP_LATITUDE'], property_details['PROP_LONGITUDE']
      base_map = folium.Map(location=[lat, lon], zoom_start=12)

      target_property_location = [lat, lon]
      popup = create_popup(property_details)

      property_group.add_child(
          folium.vector_layers.CircleMarker(
              location=target_property_location,
              tooltip=create_address(property_details['ADDRESS'], property_details['TOWN'], property_details['ZIPCODE']),
              popup=popup,
              radius=5, # Pixel radius
              # color='black', # Color of the outline of the shape
              stroke=False, # Controls if shape has an outline
              fill=True,
              fill_color='black',
              fill_opacity=0.7
          )
        )

      # Add a circle radius for nearest comps
      for key, args in radius_dict.items():
        folium.Circle(
            location=target_property_location,
            radius=args['radius'],
            tooltip=key,
            # color='black',
            fill_color=args['fill_color'],
            fill=True,
            stroke=False,
            fill_opacity=args['fill_opacity']
        ).add_to(base_map)

      return base_map, property_group

In [ ]:
def create_similar_comp(target_property: pd.Series, comp_property: pd.Series):

  # Create Boolean variables to guage target property and comp similarities

  room_diff = abs(target_property['ROOMS'] - comp_property['ROOMS'])
  sqft_diff = abs(target_property['building_sqft'] - comp_property['building_sqft'])
  similar_style = target_property['STYLEPRIMARY_SHORT'] == comp_property['STYLEPRIMARY_SHORT']
  similar_baths = target_property['BATHSTOTAL'] == comp_property['BATHSTOTAL']
  similar_rooms = room_diff < 3

  if 0 <= target_property['building_sqft'] <= 1000:
    similar_sqft = sqft_diff < (target_property['building_sqft'] * 0.25)

  elif 1001 <= target_property['building_sqft'] <= 2000:
    similar_sqft = sqft_diff < (target_property['building_sqft'] * 0.20)

  elif 2001 <= target_property['building_sqft'] <= 3500:
    similar_sqft = sqft_diff < (target_property['building_sqft'] * 0.15)

  elif 3501 <= target_property['building_sqft'] <= 5000:
    similar_sqft = sqft_diff < (target_property['building_sqft'] * 0.10)

  elif target_property['building_sqft'] >= 5001:
    similar_sqft = sqft_diff < (target_property['building_sqft'] * 0.10)

  popup = create_popup(comp_property)


  if similar_style is True:

    if (similar_baths is True) and (similar_rooms is True) and (similar_sqft is True):

      circle_marker = folium.vector_layers.CircleMarker(
                location=[comp_property['PROP_LATITUDE'], comp_property['PROP_LONGITUDE']],
                tooltip=create_address(comp_property['ADDRESS'], comp_property['TOWN'], comp_property['ZIPCODE']),
                popup=popup,
                radius=5,
                # color='black',
                stroke=False,
                fill=True,
                fill_color='blue',
                fill_opacity=0.7
            )

      return circle_marker

    else:

      circle_marker = folium.vector_layers.CircleMarker(
                location=[comp_property['PROP_LATITUDE'], comp_property['PROP_LONGITUDE']],
                tooltip=create_address(comp_property['ADDRESS'], comp_property['TOWN'], comp_property['ZIPCODE']),
                popup=popup,
                radius=5,
                # color='black',
                stroke=False,
                fill=True,
                fill_color='yellow',
                fill_opacity=0.7
            )

      return circle_marker

  else:

    circle_marker = folium.vector_layers.CircleMarker(
                location=[comp_property['PROP_LATITUDE'], comp_property['PROP_LONGITUDE']],
                tooltip=create_address(comp_property['ADDRESS'], comp_property['TOWN'], comp_property['ZIPCODE']),
                popup=popup,
                radius=5,
                # color='black',
                stroke=False,
                fill=True,
                fill_color='red',
                fill_opacity=0.7
            )

    return circle_marker

In [ ]:
def add_comp_properties(marker_group, proeprty_details: pd.Series=None):

  if proeprty_details is not None:

    town = proeprty_details['TOWN']
    county = proeprty_details['COUNTY']
    list_date = proeprty_details['LISTDATE']

    comp_properties = test_data.loc[(test_data['TOWN'] == town) & (test_data['COUNTY'] == county) & (test_data['STATUS_SHORT'] == 'SD')
                                    & ( test_data['CLOSEDDATE'] <= list_date) & (test_data['CLOSEDDATE'] > list_date - pd.Timedelta(days=90))]
    comp_properties = comp_properties.sort_values(by='LISTDATE', ascending=False)

    # if len(comp_properties) > 30:
    #   comp_properties = comp_properties.iloc[:30]

    for _, data in zip(trange(len(comp_properties)), comp_properties.iterrows()):
      row = data[1]

      try:
        # lat, lon = query_geocode(row['ADDRESS'], row['TOWN'], row['ZIPCODE'])
        marker_group.add_child(create_similar_comp(proeprty_details, row))
      except TypeError:
        pass

      except JSONDecodeError:
        pass

    return marker_group

In [ ]:
def create_comp_map(property_details: pd.Series=None):

    final_map, property_group = create_base_map(property_details)
    property_group = add_comp_properties(property_group, property_details)
    final_map.add_child(property_group)

    return final_map

In [ ]:
final_map = create_comp_map(test_data.loc[272861])

  0%|          | 0/42 [00:00<?, ?it/s]

In [ ]:
final_map